name: morphr
description: "From Figma to Flutter over-the-air."
version: 0.5.0
homepage: "https://morphr.dev"
repository: "https://github.com/intales/morphr"
license: MIT

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

executables:
  morphr: morphr_cli

dependencies:
  flutter:
    sdk: flutter

  path_parsing: ^1.1.0
  args: ^2.6.0
  interact: ^2.2.0
  http: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  diff_match_patch: ^0.4.1
  crypto: ^3.0.6
  morphr_figma: ^7.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
