// File generated by Morphr CLI - do not modify manually
import 'package:morphr/morphr.dart';

/// Default Morphr configuration for this project
const morphrOptions = MorphrCloudOptions(
  projectId: "1",
  endpoint: "http://localhost:8080",
  accessToken:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzQyOTk2ODkyLCJleHAiOjE3NDMwMDQwOTIsImF1ZCI6ImFwaSIsImlzcyI6Im1vcnBociJ9.XDg97mvCmudSSCmT-AWLzHbFEvEc77Dus6QiVdHN_sI",
  refreshToken:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzQyOTk2ODkyLCJleHAiOjE3NDU1ODg4OTIsImF1ZCI6InJlZnJlc2giLCJpc3MiOiJtb3JwaHIifQ.fzD-yfmOeFGckM1OM8L7j9okjAnTFd815k29NGfSS3U",
);
