// File generated by Morphr CLI - do not modify manually
import 'package:morphr/morphr.dart';

/// Default Morphr configuration for this project
const morphrOptions = MorphrCloudOptions(
  projectId: "1",
  endpoint: "http://localhost:8080",
  accessToken:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzQyODk1NjY5LCJleHAiOjE3NDI5MDI4NjksImF1ZCI6ImFwaSIsImlzcyI6Im1vcnBociJ9.u4axwn_tk77klWsSxc6EzaUwXVsnNuOL_ifl3qu14so",
  refreshToken:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNzQyODk1NjY5LCJleHAiOjE3NDU0ODc2NjksImF1ZCI6InJlZnJlc2giLCJpc3MiOiJtb3JwaHIifQ.0cT38k2BBSs5MKUmubyqCj5EBwICDI4AKewjwwGZzGQ",
);
