name: figma_api
version: 1.0.0
description: OpenAPI client for Figma files.

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  dio: '^5.2.0'
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
